import { SimpleGrid } from "@chakra-ui/react";
import Head from "next/head";
import PageTitle from "../components/common/page-title";
import CoursesCard from "../components/dashboard/courses-card";
import PaymentsCard from "../components/dashboard/payments-card";
import ProfileCard from "../components/dashboard/profile-card";
import TransactionsCard from "../components/dashboard/transactions-card";
import Layout from "../components/layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageTitle>Dashboard</PageTitle>
        <ProfileCard />
        <CoursesCard />
        <SimpleGrid mt={8} columns={[1, null, null, 2]} gap={8}>
          <PaymentsCard />
          <TransactionsCard />
        </SimpleGrid>
      </Layout>
    </>
  );
}
